#!/usr/bin/env python3

from atof import atof
import re
import numpy as np
from matplotlib import pyplot as plt

outfile = 'plot.out'
pat_label = re.compile('^\w+')

def load():
    data = {}
    with open(outfile) as file:
        for line in file:
            expr, value = line.split('=')
            label = pat_label.match(expr)[0]
            x, y = map(atof, value.split())
            if label == 'rt':
                label = 'original'
            elif label == 'rc':
                label = 'interpolated'
            if label in data:
                data[label].append([x, y])
            else:
                data[label] = [[x, y]]
    return {label: np.array(data[label]) for label in data}

data = load()
for l in data:
    print(f'{l}:')
    print(data[l])
sample = []
with open('plot.log') as file:
    for line in file:
        try:
            l = [i.split()[0] for i in list(map(str.strip, line.split('=')))[1:]]
            t, x, y = map(atof, l)
            sample.append([x, y])
        except ValueError:
            pass
sample = np.array(sample)
print('sample:')
print(sample, flush=True)

plt.title(r'plot figures with cubic spline interpolation')
plt.xlabel('$x$')
plt.ylabel('$y$')
for label in data:
    plt.plot(data[label][:,0], data[label][:,1], label=label)
plt.plot(sample[:,0], sample[:,1], 'k.', label='sample')
plt.legend()
plt.savefig(__file__ + '.pdf')
plt.show()
